<main id="addArticles">

        <a href="../index.php?route=articleGestion" id="retour" class="btn"><i class="fa-solid fa-chevron-left"></i></a>
        <h1>Création d'un article</h1>
        
        <form class="form" method="POST" action="index.php?route=submitFormAddArticle" enctype="multipart/form-data">
        
                <legend>Merci de renseigner les information suivantes :</legend>
        
                <?php require_once('views/bases/_errors.phtml'); ?>
                <?php require_once('views/bases/_valids.phtml'); ?>
        
                <section>
                        
                        <fieldset>
                                
                                <label  for         = "longName">Nom de l'article :</label>
                                <input  type        = "text"
                                        id          = "longName"
                                        class       = "formName"
                                        name        = "longName"
                                        value       = "<?php if(isset($newArticle) && !empty($newArticle)) { echo $newArticle['name']; } ?>"
                                        >
                                <small class='errorName'>Le nom de l'article doit comporter entre 3 et 50 caractères !</small>
                        </fieldset>

                        <fieldset>
                                
                                <label  for         = "shortName">Nom court de l'article :</label>
                                <input  type        = "text"
                                        id          = "shortName"
                                        class       = "formShortName"
                                        name        = "shortName"
                                        value       = "<?php if(isset($newArticle) && !empty($newArticle)) { echo $newArticle['shortName']; } ?>"
                                        >
                                <small class='errorShortName'>Le nom court de l'article doit comporter entre 1 et 10 caractères !</small>
                        </fieldset>

                        <fieldset>
                                <label  for         = "userfileArticle">Image : </label>
                                <input  type        = "file"
                                        accept      = "image/*"
                                        name        = "userfileArticle"
                                        id          = "userfileArticle"
                                        onchange    = "handleFiles(files)">
                                <small  class       = "form-text text-muted">Sélectionnez une image : Formats ['jpg', 'jpeg', 'gif', 'png'].</small>
                                <small  class       = "form-text text-muted">Dimensions de l'image : [220px * 240px].</small>
        
                                <div id="divImage">
                                        <label for="upload">
                                                <span id="preview"></span>
                                        </label>
                                </div>
                        </fieldset>

                        <fieldset>
                                
                                <label  for         = "price">Prix :</label>
                                <input  type        = "number"
                                        id          = "price"
                                        class       = "formPrice"
                                        name        = "price"
                                        step        = "0.01"
                                        value       = "<?php if(isset($newArticle) && !empty($newArticle)) { echo $newArticle['price']; } ?>"
                                        > €
                                <small class='errorPrice1'>Le prix de l'article, exprimé en €, doit être un nombre entier ou avec 2 décimales maximum séparées par un point !</small>
                                <small class='errorPrice2'>Le prix de l'article doit être compris entre 0 et 100 € !</small>        
                        </fieldset>

                        <fieldset>
                                
                                <label  for         = "categorie">Catégorie de l'article :</label>
                                <select name        = "categorie"
                                        class       = "formCategorie"
                                        id          = "categorie">
                                        <option value="?">?</option>
                                        <?php foreach($categories as $cat): ?>
                                                <option value="<?= htmlspecialchars($cat['id']) ?>"
                                                        <?php if($newArticle['categorie'] == $cat['id']) :?>
                                                                selected
                                                        <?php endif; ?>
                                                        ><?= htmlspecialchars($cat['name']) ?></option>
                                        <?php endforeach; ?>
                                </select>
                                <small class='errorCategorie'>Veuillez sélectionner une catégorie pour l'article !</small>
                        </fieldset>
                        
                        <fieldset>
                                <label  for         = "spl_tva">TVA sur place :</label>
                                <select name        = "spl_tva"
                                        class       = "formTvap"
                                        id          = "spl_tva">
                                        <option value="?">?</option>
                                        <?php foreach($tva_spl as $el): ?>
                                                <option value="<?= htmlspecialchars($el['id']) ?>"
                                                        <?php if($newArticle['tva_spl'] == $el['id']) :?>
                                                                selected
                                                        <?php endif; ?>
                                                        ><?= htmlspecialchars($el['name']) ?></option>
                                        <?php endforeach; ?>
                                </select>
                                <small class='errorTvap'>Veuillez sélectionner une TVA à emporter pour l'article !</small>
                        </fieldset>
                        
                        <fieldset>
                                
                                <label  for         = "emp_tva">TVA à emporter :</label>
                                <select name        = "emp_tva"
                                        class       = "formTvae"
                                        id          = "emp_tva">
                                        <option value="?">?</option>
                                        <?php foreach($tva_emp as $el): ?>
                                                <option value="<?= htmlspecialchars($el['id']) ?>"
                                                        <?php if($newArticle['tva_emp'] == $el['id']) :?>
                                                                selected
                                                        <?php endif; ?>
                                                        ><?= htmlspecialchars($el['name']) ?></option>
                                        <?php endforeach; ?>
                                </select>
                                <small class ='errorTvae'>Veuillez sélectionner une TVA à emporter pour l'article !</small>
                        </fieldset>
                        
                        <fieldset>
                                <label  for         = "active">Activation</label>
                                <select name        = "active"
                                        class       = "active"
                                        id          = "active">
                                        <option value = "1" <?php if($newArticle['activate'] == 1) :?>selected<?php endif; ?>>Oui</option>
                                        <option value = "0" <?php if($newArticle['activate'] == 0) :?>selected<?php endif; ?>>Non</option>
                                </select>
                        </fieldset>
                        
                        <fieldset>
                                <label  for         = "screen">Ecran d'affichage :</label>
                                <select name        = "screen"
                                        class       = "screen"
                                        id          = "screen">
                                        <option value="?">?</option>
                                        <?php foreach($screens as $screen): ?>
                                                <option value="<?= htmlspecialchars($screen['id']) ?>"
                                                        <?php if($newArticle['screen'] == $screen['id']) :?>
                                                                selected
                                                        <?php endif; ?>
                                                        ><?= htmlspecialchars($screen['name']) ?></option>
                                        <?php endforeach; ?>
                                </select>
                                <small class ='errorScreen'>Veuillez sélectionner un écran d'affichage pour l'article !</small>
                        </fieldset>
                        
                        <fieldset>
                                <label  for         = "code">Code barre (13 chiffres) : </label>
                                <input  type        = "text"
                                        id          = "code"
                                        name        = "code"
                                        class       = "formCode"
                                        value       = "<?php if(isset($newArticle) && !empty($newArticle)) { echo $newArticle['codeBarre']; } ?>">
                                        
                                        <small class ='errorCode'>Veuillez entrer un code barre de 13 chiffres ou laisser le champ vide !</small>
                        </fieldset>

                        <fieldset>
                                <input  type    = "hidden"
                                        name    = "token"
                                        value   = "<?= $token ?>">
                        </fieldset>

                </section>
                <fieldset>
                        <input  type    = "submit"
                                name    = "submit"
                                value   = "Soumettre"
                                class   = "btn colorGreen buttonSubmit">
                </fieldset>

        </form>
        <script src="assets/js/preview.js"></script>
        <script type="module" src="assets/js/form.js"></script>
</main>