<!-- <?php var_dump($data); ?> -->
<main id ="addAdressForm">

        <a href="index.php?route=displayOneCustomer&id=<?= $data["customer"]["id"] ?>" id="retour" class="btn"><i class="fa-solid fa-chevron-left"></i></a>
        <h1><?php if(isset($data['customer']['adress']) && !empty($data['customer']['adress'])) { 
                echo "Modification de l'";}
                else{ echo "Création d'une ";} ?>adresse client</h1>

        <form id="addAdressForm" method="POST" action="index.php?route=addAdress&id=<?= $data["customer"]["id"] ?>" enctype="multipart/form-data">

        <legend>Merci de renseigner les informations suivantes</legend>

        <?php require_once('views/bases/_errors.phtml'); ?>
        <?php require_once('views/bases/_valids.phtml'); ?>

        <section>

                <fieldset>
                        <label  for     = "adress">Adresse</label>
                        <input  type    = "text"
                                id      = "adress"
                                name    = "adress"
                                value   = "<?php if(isset($data['customer']['adress']) && !empty($data['customer']['adress'])) { echo $data['customer']['adress']; } ?>"
                        >
                        <small id="errorAdress">Merci de rentrer une adresse valide</small>
                </fieldset>

                <fieldset>
                        <label  for     = "zipcode">Code postal</label>
                        <input  type    = "number"
                                id      = "zipcode"
                                name    = "zipcode"
                                value   = "<?php if(isset($data['customer']['zipcode']) && !empty($data['customer']['zipcode'])) { echo $data['customer']['zipcode']; } ?>"
                        >
                        <small id="errorZipcode">Merci de saisir un code postal valide</small>
                </fieldset>        

                <fieldset>
                        <label  for     = "city">Ville</label>
                        <input  type    = "text"
                                id      = "city"
                                name    = "city"
                                value   = "<?php if(isset($data['customer']['city']) && !empty($data['customer']['city'])) { echo $data['customer']['city']; } ?>"
                        >
                        <small id="errorCity">Merci de saisir une ville valide</small>
                </fieldset>

                <fieldset>
                        <label  for     = "country">Pays</label>
                        <select name="country"
                                id="country">

                                <?php if(isset($data['customer']['pays']) && !empty($data['customer']['pays'])) { ?>
                                <option value="<?= $data['customer']['country_id'] ?>"><?= $data['customer']['pays'] ?></option>
                                <?php } else { ?>
                                <option value="">--Choisir votre Pays--</option>
                                <?php } ?>
                                <?php foreach($data["countries"] as $country){ ?>
                                <option value="<?= $country["id"]; ?>"><?= $country["name"]; ?></option>
                                <?php } ?>
                        </select>
                        <small id="errorCountry">Merci de saisir un pays valide</small>
                </fieldset>

                <fieldset>
                        <input  type    = "hidden"
                                name    = "token"
                                value   = "<?= $token ?>">
                </fieldset>

        </section>
        <fieldset>
                <input  type    = "submit"
                        name    = "submit"
                        value   = "Valider"
                        class   = "btn colorGreen">
                </fieldset>

        </form>
<script src="assets/js/preview.js"></script>
<script type="module" src="assets/js/form.js"></script>
</main>