<main id="addCustomers">
        <section>
                <h1>Création de compte !</h1>
        </section>
        
        <form method="POST" action="index.php?route=submitFormAddCustomer" enctype="multipart/form-data">
        
                <legend>Merci de renseigner les information suivantes :</legend>
        
                <?php require_once('views/bases/_errors.phtml'); ?>
                <?php require_once('views/bases/_valids.phtml'); ?>
        
                <section>
                        
                        <fieldset>
                                <label  for     = "lastname">Nom :</label>
                                <input  type    = "text"
                                        id      = "lastname"
                                        name    = "lastname"
                                        value   = "<?php if(isset($newCustomer) && !empty($newCustomer)) { echo $newCustomer['lastname']; } ?>">
                        </fieldset>
                        
                        <fieldset>
                                <label  for     = "firstname">Prénom :</label>
                                <input  type    = "text"
                                        id      = "firstname"
                                        name    = "firstname"
                                        value   = "<?php if(isset($newCustomer) && !empty($newCustomer)) { echo $newCustomer['firstname']; } ?>">
                        </fieldset>

                        <fieldset>
                                <label  for     = "birthday">Date de naissance :</label>
                                <input  type    = "date"
                                        id      = "birthday"
                                        name    = "birthday"
                                        value   = "<?php if(isset($newCustomer) && !empty($newCustomer)) { echo $newCustomer['birthday']; } ?>">
                        </fieldset>

                        <fieldset>
                                <label  for     = "email">email :</label>
                                <input  type    = "email"
                                        id      = "email"
                                        name    = "email"
                                        value   = "<?php if(isset($newCustomer) && !empty($newCustomer)) { echo $newCustomer['email']; } ?>">
                        </fieldset>

                        <fieldset>
                                <label  for         = "password">Mot de passe :</label>
                                <input  type        = "password"
                                        id          = "password"
                                        name        = "password"
                                        placeholder = "Choisissez un mot de passe"
                                        value       = "<?php if(isset($newCustomer) && !empty($newCustomer)) { echo $newCustomer['password']; } ?>">
                                <small>Contenant 8 caractères minimum avec 1 majuscule, 1 minuscule, 1 chiffre et un caractère spécial !</small>
                        </fieldset>

                        <fieldset>
                                <label  for     = "confirm_password">Confirmez le mot de passe :</label>
                                <input  type    = "password"
                                        id      = "confirm_password"
                                        name    = "confirm_password">
                        </fieldset>

                        <fieldset>
                                <label  for     = "rfid">RFID :</label>
                                <input  type    = "text"
                                        id      = "rfid"
                                        name    = "rfid"
                                        value   = "<?php if(isset($newCustomer) && !empty($newCustomer)) { echo $newCustomer['rfid']; } ?>">
                        </fieldset>

                        <fieldset>
                                <input  type    = "hidden"
                                        name    = "token"
                                        value   = "<?= $token ?>">
        
                </section>
                <fieldset>
                        <input  type    = "submit"
                                name    = "submit"
                                value   = "Soumettre"
                                class   = "btn colorGreen">
                </fieldset>
        </form>
</main>
