<!-- <?php var_dump($data); ?> -->
<main id ="addCustomerAdressForm">

        <a href="../index.php?route=displayOneCustomer&id=<?= $data["customer"]["id"] ?>" id="retour" class="btn"><i class="fa-solid fa-chevron-left"></i></a>
        <h1>Création d'une adresse client</h1>

        <form id="addCustomerForm" method="POST" action="index.php?route=submitFormAddCustomer" enctype="multipart/form-data">

        <legend>Merci de renseigner les informations suivantes</legend>

        <?php require_once('views/bases/_errors.phtml'); ?>
        <?php require_once('views/bases/_valids.phtml'); ?>

        <section>

                <fieldset>
                        <label  for     = "adress">Adresse</label>
                        <input  type    = "text"
                                id      = "adress"
                                name    = "adress"
                                value   = "<?php if(isset($newCustomer) && !empty($newCustomer)) { echo $newCustomer['lastname']; } ?>"
                        >
                        <small id="errorAdress">Votre adresse doit comprendre entre 5 et 50 caractères</small>
                </fieldset>

                <fieldset>
                        <label  for     = "zipcode">Code postal</label>
                        <input  type    = "number"
                                id      = "zipcode"
                                name    = "zipcode"
                                value   = "<?php if(isset($newCustomer) && !empty($newCustomer)) { echo $newCustomer['firstname']; } ?>"
                        >
                        <small id="errorZipcode">Votre code postal doit comprendre 5 chiffres</small>
                </fieldset>        

                <fieldset>
                        <label  for     = "city">Ville</label>
                        <input  type    = "text"
                                id      = "city"
                                name    = "city"
                                value   = "<?php if(isset($newCustomer) && !empty($newCustomer)) { echo $newCustomer['birthday']; } ?>">
                        <small id="errorCity">Votre ville doit comprendre entre 2 et 50 caractères</small>
                </fieldset>

                <fieldset>
                        <label  for     = "country">Pays</label>
                        <select name="country"
                                id="country">
                                <option value="">--Choisir votre Pays--</option>
                                <?php foreach($data["countries"] as $country){ ?>
                                <option value="<?= $country["id"]; ?>"><?= $country["name"]; ?></option>
                                <?php } ?>
                        </select>
                        <small id="errorCountry">Merci de rentrer un pays valide</small>
                </fieldset>

                <fieldset>
                        <input  type    = "hidden"
                                name    = "token"
                                value   = "<?= $token ?>">
                </fieldset>

        </section>
        <fieldset>
                <input  type    = "submit"
                        name    = "submit"
                        value   = "Valider"
                        class   = "btn colorGreen">
                </fieldset>

        </form>
<script src="assets/js/preview.js"></script>
<script type="module" src="assets/js/form.js"></script>
</main>