<main id="addOptions">
    <h1>Création d'option pour les articles</h1>
    

        
        <?php require_once('views/bases/_errors.phtml'); ?>
        <?php require_once('views/bases/_valids.phtml'); ?>
        
        
        <section>
            <fieldset>
                <label  for         = "optionName">Nom de l'option :</label>  
                <input  type        = "text"
                        id          = "optionName"
                        name        = "optionName"
    
                        value       = "<?php if(isset($newOption) && !empty($newOption)) { echo $newOption['name']; } ?>"
                        required>
            </fieldset>        
            


            <label  for         = "optionPrice">Prix de l'option :</label>
            <input  type        = "number"
                    id          = "optionPrice"
                    name        = "optionPrice"

                    step        = "0.01"
                    value       = "<?php if(isset($newOption) && !empty($newOption)) { echo $newOption['price']; } ?>"
                    required> €

            <fieldset>
                <label  for         = "optionShortName">Nom court de l'option :</label>
                <input  type        = "text"
                        id          = "optionShortName"
                        name        = "optionShortName"
    
                        value       = "<?php if(isset($newOption) && !empty($newOption)) { echo $newOption['shortName']; } ?>"
                        required>
                
            </fieldset>

            
            <fieldset>
                <label  for         = "optionPrice">Prix de l'option :</label>
                <input  type        = "text"
                        id          = "optionPrice"
                        name        = "optionPrice"
    
                        step        = "0.01"
                        value       = "<?php if(isset($newOption) && !empty($newOption)) { echo $newOption['price']; } ?>"
                        required>
                
            </fieldset>
            
            <fieldset>
                <label  for         = "userfileOption">Image pour l'option: </label>
                <input  type        = "file"
                        accept      = "image/*"
                        name        = "userfileOption"
                        id          = "userfileOption"
                        onchange    = "handleFiles(files)">
                <small  class       = "form-text text-muted">Sélectionnez une image : Formats ['jpg', 'jpeg', 'gif', 'png'].</small>
                <small  class       = "form-text text-muted">Dimensions de l'image : [220px * 240px].</small>
            </fieldset>
            
            <fieldset>
                <label  for         = "categorieCondiment">Catégorie de l'option :</label>
                <select name        = "categorieCondiment"
                        class       = "categorieCondiment"
                        id          = "categorieCondiment">
                    <option value="?">?</option>
                    <?php foreach($categories as $categorie){ ?>
                    <option value="<?= htmlspecialchars($categorie['id'])?>"><?=$categorie['name']?></option>
                    <?php }?>
                 </select>
            </fieldset>
    
        </section>

        <fieldset>
            <input      type    = "submit"
                        name    = "submit"
                        value   = "Soumettre"
                        class   = "btn colorGreen">
        </fieldset>    


    </form>

<script type="text/javascript" src="assets/js/form.js"></script>
</main>