<main id="addOptions">

    <a href="index.php?route=articleGestion" id="retour" class="btn"><i class="fa-solid fa-chevron-left"></i></a>
    <h1>Création d'option pour les articles</h1>

    <?php require_once('views/bases/_errors.phtml'); ?>
    <?php require_once('views/bases/_valids.phtml'); ?>
        
    <form class="form" method="POST" action="index.php?route=submitFormAddOption" enctype="multipart/form-data">
        <section>
            
            <fieldset>
                
                <label  for         = "optionName">Nom de l'option :</label>  
                <input  type        = "text"
                        id          = "optionName"
                        class       = "formName"
                        name        = "optionName"
                        value       = "<?php if(isset($newOption) && !empty($newOption)) { echo $newOption['name']; } ?>"
                        >
                <small class='errorName'>Le nom de l'option doit comporter entre 3 et 50 caractères !</small>        
            </fieldset>        
            

            <fieldset>
                
                <label  for         = "optionShortName">Nom court de l'option :</label>
                <input  type        = "text"
                        id          = "optionShortName"
                        class       = "formShortName"
                        name        = "optionShortName"
                        value       = "<?php if(isset($newOption) && !empty($newOption)) { echo $newOption['shortName']; } ?>"
                        >
                <small class='errorShortName'>Le nom court de l'option doit comporter entre 1 et 10 caractères !</small>
            </fieldset>

            
            <fieldset>
                
                <label  for         = "optionPrice">Prix de l'option :</label>
                <input  type        = "number"
                        id          = "optionPrice"
                        class       = "formPrice"
                        name        = "optionPrice"
                        step        = "0.01"
                        value       = "<?php if(isset($newOption) && !empty($newOption)) { echo $newOption['price']; } ?>"
                        >
                <small class='errorPrice1'>Le prix de l'option, exprimé en €, doit être un nombre entier ou avec 2 décimales maximum séparées par un point !</small>
                <small class='errorPrice2'>Le prix de l'option doit être compris entre 0 et 100 € !</small>
            </fieldset>
            
            <fieldset>
                <label  for         = "userfileOption">Image pour l'option: </label>
                <input  type        = "file"
                        accept      = "image/*"
                        name        = "userfileOption"
                        id          = "userfileOption"
                        onchange    = "handleFiles(files)">
                <small  class       = "form-text text-muted">Sélectionnez une image : Formats ['jpg', 'jpeg', 'gif', 'png'].</small>
                <small  class       = "form-text text-muted">Dimensions de l'image : [220px * 240px].</small>
            </fieldset>
            
            <fieldset>
                
                
                <label  for         = "categorieCondiment">Catégorie de l'option :</label>
                <select name        = "categorieCondiment"
                        class       = "formCategorie"
                        id          = "categorieCondiment">
                    <option value="?">?</option>
                    <?php foreach($categories as $categorie){ ?>
                    <option value="<?= htmlspecialchars($categorie['id'])?>"><?=$categorie['name']?></option>
                    <?php }?>
                 </select>
                 <small class='errorCategorie'>Veuillez sélectionner une catégorie pour l'option !</small>
            </fieldset>
    
        </section>

        <fieldset>
            <input      type    = "submit"
                        id      = "optionSubmit"
                        class   = "buttonSubmit btn colorGreen"
                        name    = "submit"
                        value   = "Soumettre">
        </fieldset>    


    </form>
<script src="assets/js/preview.js"></script>
<script type="module" type="text/javascript" src="assets/js/form.js"></script>
</main>