<main id="articleOption">
<a href="index.php?route=articleGestion" id="retour" class="btn"><i class="fa-solid fa-chevron-left"></i></a>
    <section>
    <?php require_once('views/bases/_errors.phtml'); ?>
    <?php require_once('views/bases/_valids.phtml'); ?>
        <?php
        $model = new \Models\OptionsManager();
        $links = $model->getOptionsLink($article['id']);
        ?>
        <article>
        <img src="assets/uploads/articles/<?= htmlspecialchars($article['categories_id'])?>/<?= htmlspecialchars($article['picture']) ?>">
            <h3><?= htmlspecialchars($article['name']) ?></h3>
            <input type='hidden' id="articleId" value="<?= $article['id']?>">
            </p><?= htmlspecialchars($article['price']) ?> €</p>
        
            <span><?= htmlspecialchars($article['shortName']) ?></span>
            <ul>Options :</ul>
            <?php foreach($links as $link):
            $model = new \Models\OptionsManager();
            $option = $model->getOptionById($link['articlesOptionsListing_id']);
        ?><li><?=$option['name'];?><a href ="index.php?route=deleteLink&articleId=<?=$article['id']?>&optionId=<?=$option['id']?>"><i class="fa-solid fa-square-xmark" style="color: #e00b0b;"></i></a></li>
            
            <?php
            endforeach;?>

        <h4>AJOUT D'OPTION</h4>
        <p>Choisissez la catégorie d'option à afficher !<p>
        <select     name        = "categorieOption"
                    class       = "formCategorieOption"
                    id          = "categorieOption">
                    <option value="?">?</option>
                        <?php foreach($categories as $categorie){ ?>
                        <option value="<?= htmlspecialchars($categorie['id'])?>"><?=htmlspecialchars($categorie['name'])?></option>
                        <?php }?>
            </select>
            <div id='targets'>
            </div>
            <br>
            <br>
            <br>
    </section>
    <script type="text/javascript" src="assets/js/ajaxOption.js"></script>