<?php
    
?>    

<section>
<?php 

if(empty($articlesFind)){
?> <small>Il n'y a pas d'article dans cette catégorie !</small>
<?php
}
else{
foreach($articlesFind as $article): 
    $model = new \Models\OptionsManager();
    $links = $model->getOptionsLink($article['id']);

?>
            <article>
                <img src="assets/uploads/articles/<?= htmlspecialchars($article['categories_id'])?>/<?= htmlspecialchars($article['picture']) ?>">
                    <h3><?= htmlspecialchars($article['name']) ?></h3>
                
                    </p><?= htmlspecialchars($article['price']) ?> €</p>
                
                    <span><?= htmlspecialchars($article['shortName']) ?></span>
                    <ul>Options :</ul>
                    <?php foreach($links as $link):
                    $model = new \Models\OptionsManager();
                    $option = $model->getOptionById($link['articlesOptionsListing_id']);
                    ?> <li><?=$option['name'];?></li>
                    <?php
                    endforeach;?>
                    <br>
                    <a href="index.php?route=articleOption&id=<?= htmlspecialchars($article['id']) ?>" class="btn colorGreen">
                        AJOUTER UNE OPTION
                    </a>
            </article>
        <?php endforeach;
} ?>
