<main id="articleOption">
<a href="index.php?route=articleGestion" id="retour" class="btn"><i class="fa-solid fa-chevron-left"></i></a>
<h1>Ajout d'Options </h1>
    <section>
    <?php require_once('views/bases/_errors.phtml'); ?>
    <?php require_once('views/bases/_valids.phtml'); ?>
        <?php
        $model = new \Models\OptionsManager();
        $links = $model->getOptionsLink($article['id']);
        ?>
        <article>
            <div>
                <img src="assets/uploads/articles/<?= htmlspecialchars($article['categories_id'])?>/<?= htmlspecialchars($article['picture']) ?>">
            
                <h2><?= htmlspecialchars($article['name']) ?></h2>
                <input type='hidden' id="articleId" value="<?= $article['id']?>">
                </p><?= htmlspecialchars($article['price']) ?> €</p>
                
            </div>
            <div>Options :
            <ul>
            <?php foreach($links as $link):
            $model = new \Models\OptionsManager();
            $option = $model->getOptionById($link['articlesOptionsListing_id']);
        ?><li><?=$option['name'];?></li>  <a href ="index.php?route=deleteLink&articleId=<?=$article['id']?>&optionId=<?=$option['id']?>"><i class="fa-solid fa-square-xmark" style="color: #e00b0b;"></i></a>
            
            <?php
            endforeach;?>
            </ul>
            </div>
        </article>
        <article>

        <h2>Choisissez la catégorie d'option à afficher !</h2>
        <select     name        = "categorieOption"
                    class       = "formCategorieOption"
                    id          = "categorieOption">
                    <option value="?">?</option>
                        <?php foreach($categories as $categorie){ ?>
                        <option value="<?= htmlspecialchars($categorie['id'])?>"><?=htmlspecialchars($categorie['name'])?></option>
                        <?php }?>
            </select>
            <div id='targets'>
            </div>
        </article>
    </section>
    <script type="module" type="text/javascript" src="assets/js/index.js"></script>