<!-- <?php var_dump($data); ?> -->
<main id="customerDetails">

    <a href="index.php?route=customers" id="retour" class="btn"><i class="fa-solid fa-chevron-left"></i></a>
    <h1>Utilisateur</h1>

    <?php   if(empty($data['customer'])){
                        require_once('views/bases/_valids.phtml');
                }
                else{?>

    <section>
        <?php if($data['customerDetails']->getAdress()==null){ ?>
        <a href="index.php?route=addCustomerAdress&id=<?= $data["customer"]->getId() ?>" id="retour" class="btn colorGreen">Ajouter une adresse</a>
        <?php } else{ ?>
        <a href="index.php?route=addCustomerAdress&id=<?= $data["customer"]->getId() ?>" id="retour" class="btn colorYellow">Modifier l'adresse</a>
        <?php } ?>
        <section>
            <form method="POST" action="index.php?route=activationCustomer&id=<?= $customer->getId(); ?>">
                <fieldset>
                        <input  type    = "hidden"
                                name    = "token"
                                value   = "<?= $token ?>">
                </fieldset>

                <fieldset>
                        <input  type    = "submit"
                                name    = "submit"
                                <?php if($data['customer']->getValids()==1){
                                        echo '  value   = "Valider la création du nouvel utilisateur"
                                                class   = "btn colorGreen"
                                        ';}
                                        else if($data['customer']->getValids()==2){
                                        echo '  value   = "Désactiver"
                                                class   = "btn colorYellow"
                                        ';}
                                        else{
                                        echo '  value   = "Activer"
                                                class   = "btn colorGreen"
                                        ';}
                                ?>
                        >
                </fieldset>
            </form>
            
            <?php if($data['customer']->getValids()==2){ ?>
            <a href="index.php?route=updateCustomer&id=<?= $customer->getId(); ?>" class="btn colorYellow">Modifier</a>
            <?php }?>
            
            <button id="deleteBtn" class="btn colorRed">Supprimer</button>

        </section>
    </section>

    <section class="chats-box">
        <ul>
            <?php if( $customer !== [] ) : ?>
                <table>
                    <thead>
                        <tr>
                            <th>Nom</th>
                            <th>Prénom</th>
                            <th>Email</th>
                            <th>Date de naissance</th>
                            <th>Adresse</th>
                            <th>Statut</th>
                        </tr>
                    </thead>
                    <tbody <?php if($data['customer']->getValids()==3){echo'class="inactif"';}?>>
                        <tr>
                            <td><?= htmlspecialchars($customer->getLastname()); ?></td>
                            <td><?= htmlspecialchars($customer->getFirstname()); ?></td>
                            <td><?= htmlspecialchars($customer->getEmail()); ?></td>
                            <td><?= htmlspecialchars(date_format(date_create($customer->getBirthday()), 'd-m-Y')); ?></td>
                            <?php if( $customerDetails->getAdress() !== null ) : ?>
                                <td><?= $customerDetails->getAdress() . ' '. $customerDetails->getZipcode() . ' ' . $customerDetails->getCity() . ' [' . $customerCountry->getName() . ']' ?></td>
                            <?php else : ?>
                                <td>Pas d'adresse.</td>
                            <?php endif; ?>
                            <td><?= $customerValids->getStatut(); ?></td>
                        </tr>
                    </tbody>
                </table>
            <?php else : ?>
                <li>Cette section est vide.</li>
            <?php endif; ?>
        </ul>
    </section>
    <section id="backdrop">
        <section id="modal">
                    <p><i id="cancelIcon" class="fa-solid fa-xmark"></i></p>
                    <h2>Etes vous sûr de vouloir supprimer <?= htmlspecialchars($customer->getLastname()). " " .htmlspecialchars($customer->getFirstname()); ?> de la base clients ?</h2>
                    <section>
                        <button id="cancelBtn" class="btn colorYellow">Annuler</button>

                        <form method="POST" action="index.php?route=deleteCustomer&id=<?= $customer->getId(); ?>">
                            <fieldset>
                                    <input  type    = "hidden"
                                            name    = "token"
                                            value   = "<?= $token ?>">
                            </fieldset>

                            <fieldset>
                                    <input  type    = "submit"
                                            name    = "submit"
                                            value   = "Supprimer"
                                            class   = "btn colorRed"
                                    >
                                    <?php if($data['customer']->getValids()==2){ ?>
                                        <?php } ?>

                            </fieldset>
                        </form>
                    </section>

        </section>
    </section>

    <?php } ?>

</main>
<script type="module" src="assets/js/index.js"></script>
