<main id="customerDetails">
    <section>
        <h1>Utilisateurs</h1>
    </section>

    <section class="chats-box">
        <ul>
            <?php if( $customer !== [] ) : ?>
                <table>
                    <thead>
                        <tr>
                            <th>Nom</th>
                            <th>Prénom</th>
                            <th>Email</th>
                            <th>Date de naissance</th>
                            <th>Adresse</th>
                            <th>Statut</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td><?= $customer->getLastname(); ?></td>
                            <td><?= $customer->getFirstname(); ?></td>
                            <td><?= $customer->getEmail(); ?></td>
                            <td><?= $customer->getBirthday(); ?></td>
                            <?php if( $customerDetails->getAdress() !== null ) : ?>
                                <td><?= $customerDetails->getAdress() . ' '. $customerDetails->getCp() . ' ' . $customerDetails->getCity() . ' [' . $customerCountry->getName() . ']' ?></td>
                            <?php else : ?>
                                <td>Pas d'adresse.</td>
                            <?php endif; ?>
                            <td><?= $customerValids->getStatut(); ?></td>
                        </tr>
                    </tbody>
                </table>
            <?php else : ?>
                <li>Cette section est vide.</li>
            <?php endif; ?>
        </ul>
    </section>

    <section>
        <a href="../index.php?route=customers" id="retour" class="btn colorBlue">Retour</a>
    </section>

</main>
