<main id="customerDetails">

    <a href="../index.php?route=customers" id="retour" class="btn colorBlue"><i class="fa-solid fa-chevron-left"></i></a>
    <h1>Utilisateurs</h1>

    <section class="chats-box">
        <ul>
            <?php if( $customer !== [] ) : ?>
                <table>
                    <thead>
                        <tr>
                            <th>Nom</th>
                            <th>Prénom</th>
                            <th>Email</th>
                            <th>Date de naissance</th>
                            <th>Adresse</th>
                            <th>Statut</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td><?= htmlspecialchars($customer->getLastname()); ?></td>
                            <td><?= htmlspecialchars($customer->getFirstname()); ?></td>
                            <td><?= htmlspecialchars($customer->getEmail()); ?></td>
                            <td><?= htmlspecialchars(date_format(date_create($customer->getBirthday()), 'd-m-Y')); ?></td>
                            <?php if( $customerDetails->getAdress() !== null ) : ?>
                                <td><?= $customerDetails->getAdress() . ' '. $customerDetails->getCp() . ' ' . $customerDetails->getCity() . ' [' . $customerCountry->getName() . ']' ?></td>
                            <?php else : ?>
                                <td>Pas d'adresse.</td>
                            <?php endif; ?>
                            <td><?= $customerValids->getStatut(); ?></td>
                        </tr>
                    </tbody>
                </table>
            <?php else : ?>
                <li>Cette section est vide.</li>
            <?php endif; ?>
        </ul>
    </section>
</main>
