<main id="gestionCategories">

    <a href="../index.php" id="retour" class="btn"><i class="fa-solid fa-chevron-left"></i></a>
    <h1>CATEGORIES</h1>
    
    <section class="container">
        <?php if(empty($categories)) : ?>
            <p>Aucun article dans cette catégorie !</p>
        <?php else: ?>
            <section class="leftElement">
                <?php foreach($data["categories"] as $categorie) : ?>
                    <article class="dispositionCategories">

                        <img src="assets/uploads/categories/<?= htmlspecialchars($categorie['picture']) ?>" alt="Image de la catégorie" <?php if($categorie['activate']==0){ ?>class="inactif"<?php } ?>/>
                        <p <?php if($categorie['activate']==0){ ?>class="inactif"<?php } ?>><?= htmlspecialchars($categorie['name']) ?></p>

                        <section>
                            <form method="POST" action="index.php?route=activationCategorie&id=<?= $categorie['id'] ?>">
                                <input  type    = "hidden"
                                        name    = "id"
                                        value   =  "<?= $categorie['id'] ?>"
                                >
                    
                                <input  type    = "hidden"
                                        name    = "token"
                                        value   =   <?php foreach($_SESSION['tokenGestionCategories'] as $elem) : ?>
                                                        <?php if(intval($elem['id']) == $categorie['id']) : ?>
                                                            <?= $elem['token'] ?>
                                                        <?php endif; ?>
                                                    <?php endforeach; ?>
                                >
                    
                                <input  type    = "submit"
                                        name    = "submit"
                                        <?php   if($categorie['activate']==1){
                                                    echo'   value   = "Désactiver"
                                                            class   = "btn colorYellow"
                                                        ';}
                                                else{
                                                    echo'   value   = "Activer"
                                                            class   = "btn colorGreen"
                                                        ';}
                                        ?>
                                >
                            </form>

                            <form method="POST" action="index.php?route=delCat&id=<?=$categorie['id']?>">
                                <input  type    = "hidden"
                                        name    = "token"
                                        value   =   <?php foreach($_SESSION['tokenGestionCategories'] as $elem) : ?>
                                                        <?php if(intval($elem['id']) == $categorie['id']) : ?>
                                                            <?= $elem['token'] ?>
                                                        <?php endif; ?>
                                                    <?php endforeach; ?>
                                >
                                <input  type    = "hidden"
                                        name    = "id"
                                        value   = "<?= $categorie['id'] ?>">
            
                                <input  type    = "submit"
                                        name    = "submit"
                                        value   = "Supprimer"
                                        class   = "btn colorRed">
                            </form>

                        </section>
                    </article>
                <?php endforeach; ?>

                <?php require_once('views/bases/_errors.phtml'); ?>
                <?php require_once('views/bases/_valids.phtml'); ?>
            </section>
        <?php endif; ?>
    
    <div class="rightElement">
        <section>
            <form method="POST" action="index.php?route=submitFormAddCategorie" enctype="multipart/form-data">
    
                <h2>Ajouter une catégorie</h2>
                <legend>Merci de renseigner les information suivantes :</legend>
    
                <fieldset>
                    <label  for     = "name">Nom de la catégorie :</label>
                    <input  type    = "text"
                            id      = "name"
                            name    = "name"
                            value   = "">
                </fieldset>
                
                <fieldset>
                    <label  for         = "fileCategorie">Image : </label>
                    <input  type        = "file"
                            accept      = "image/*"
                            name        = "fileCategorie"
                            id          = "fileCategorie"
                            onchange    = "handleFiles(files)">

                    <small  class       = "form-text text-muted">Sélectionnez une image : Formats ['jpg', 'jpeg', 'gif', 'png'].</small>
                    <small  class       = "form-text text-muted">Dimensions de l'image : [220px * 240px].</small>

                    <div id="divImage">
                            <label for="upload">
                                    <span id="preview"></span>
                            </label>
                    </div>
                </fieldset>

                <fieldset>
                    <input  type    = "hidden"
                            name    = "token"
                            value   = "<?= $token ?>">
                </fieldset>
    
                <fieldset>
                    <input  type    = "submit"
                            name    = "submit"
                            value   = "Ajouter"
                            class   = "btn colorGreen">
                </fieldset>
            </form>
        </section>
    </div>
    </section>
    <script src="assets/js/preview.js"></script>
</main>