<section>
    <h1>TVA</h1>
</section>

<section class="container">
    <?php if(empty($tva)) : ?>
        <p>Aucune TVA enregistrée actuellement !</p>
    <?php else: ?>
        <section class="leftElement">
            <?php foreach($tva as $element => $key) : ?>
                <article class="dispositionCategories">
                    <p><?= htmlspecialchars($key['name']) ?></p>

                    <form method="POST" action="index.php?route=delCat&id=<?= $key['id'] ?>">

                    <input  type    = "hidden"
                            name    = "token"
                            value   =  "<?= $key['id'] ?>" >

                    <input  type    = "hidden"
                            name    = "id"
                            value   =   <?php foreach($_SESSION['tokenGestionTva'] as $elem) : ?>
                                            <?php if(intval($elem['id']) == $key['id']) : ?>
                                                <?= $elem['token'] ?>
                                            <?php endif; ?>
                                        <?php endforeach; ?>
                    >

                    <input  type    = "submit"
                            name    = "submit"
                            value   = "Supprimer"
                            class   = "btn colorRed">
                    </form>
                </article>
            <?php endforeach; ?>
            <?php require_once('views/bases/_errors.phtml'); ?>
            <?php require_once('views/bases/_valids.phtml'); ?>
        </section>
    <?php endif; ?>

<div class="rightElement">
    <section>
        <form method="POST" action="index.php?route=addTva" enctype="multipart/form-data">

            <h2>Ajouter une TVA</h2>
            <legend>Merci de renseigner les information suivantes :</legend>

            </br></br>
                    <label  for     = "name">Nom de la catégorie :</label>
                    <input  type    = "text"
                            id      = "name"
                            name    = "name"
                            value   = "test">
                </br></br>
                    <label  for         = "fileCategorie">Image : </label>
                    <input  type        = "file"
                            accept      = "image/*"
                            name        = "fileCategorie"
                            id          = "fileCategorie"
                            onchange    = "handleFiles(files)">
                </br>
                    <small  class       = "form-text text-muted">Sélectionnez une image : Formats ['jpg', 'jpeg', 'gif', 'png'].</small>
                    <small  class       = "form-text text-muted">Dimensions de l'image : [220px * 240px].</small>
                </br>
                    <div id="divImage">
                            <label for="upload">
                                    <span id="preview"></span>
                            </label>
                    </div>
                </br>
                    <input  type    = "hidden"
                            name    = "token"
                            value   = "<?= $token ?>">

                    <input  type    = "submit"
                            name    = "submit"
                            value   = "Ajouter"
                            class   = "btn colorGreen">
        </form>
    </section>
</div>
</section>
<script src="assets/js/preview.js"></script>

