<main id="gestionTVAPM">

    <a href="../index.php" id="retour" class="btn"><i class="fa-solid fa-chevron-left"></i></a>
    <h1>Moyens de paiement</h1>
    
    <section class="container">
        <?php if(empty($data["paymentMethod"])) : ?>
        <p>Aucun moyen de paiement enregistré actuellement !</p>
        <?php else: ?>
        <section class="leftElement">
            <?php foreach($data["paymentMethod"] as $PM) : ?>
            <article class="dispositionCategories">

                <p <?php if($PM['activate']==0){ ?>class="inactif"<?php } ?>><?= htmlspecialchars($PM['name']) ?></p>
    
                <form method="POST" action="index.php?route=activationPM&id=<?= $PM['id'] ?>">
    
                    <input  type    = "hidden"
                            name    = "id"
                            value   =  "<?= $PM['id'] ?>" >
        
                    <input  type    = "hidden"
                            name    = "token"
                            value   =   <?php foreach($_SESSION['tokenGestionTva'] as $elem) : ?>
                                            <?php if(intval($elem['id']) == $PM['id']) : ?>
                                                <?= $elem['token'] ?>
                                            <?php endif; ?>
                                        <?php endforeach; ?>
                    >
        
                    <input  type    = "submit"
                            name    = "submit"
                            <?php   if($PM['activate']==1){
                                        echo'   value   = "Désactiver"
                                                class   = "btn colorYellow"
                                            ';}
                                    else{
                                        echo'   value   = "Activer"
                                                class   = "btn colorGreen"
                                            ';}
                            ?>
                    >
                </form>
            </article>
            <?php endforeach; ?>
        </section>
        <?php endif; ?>
    
        <div class="rightElement">
            <section>
                <form method="POST" action="index.php?route=addPaymentMethod" id="addPMForm" enctype="multipart/form-data">
        
                    <h2>Ajouter un moyen de paiement</h2>
                    <legend>Merci de renseigner les information suivantes :</legend>

                    <fieldset>
                        <label  for         = "value">Moyen de paiment</label>
                        <input  type        = "text"
                                id          = "PMName"
                                name        = "name"
                                pattern     = "[A-Za-z' -]{2,20}"
                                placeholder = "exemple : CHEQUE">
                        <small id="PMError"> Ce champs doit contenir entre 2 et 20 caractères</small>
                    </fieldset>
    
                    <fieldset>
                            <input  type    = "hidden"
                                    name    = "token"
                                    value   = "<?= $token ?>">
                    </fieldset>
        
                    <fieldset>
                            <input  type    = "submit"
                                    name    = "submit"
                                    value   = "Ajouter"
                                    class   = "btn colorGreen">
                    </fieldset>
                </form>
                <section>
                <?php require_once('views/bases/_errors.phtml'); ?>
                <?php require_once('views/bases/_valids.phtml'); ?>
                </section>
            </section>
        </div>
    </section>
    <script src="assets/js/preview.js"></script>
    <script src="assets/js/gestionPM.js"></script>
</main>