<main id="gestionTVAPM">
    
    <a href="../index.php" id="retour" class="btn"><i class="fa-solid fa-chevron-left"></i></a>
    <h1>TVA</h1>
    
    <section class="container">
        <?php if(empty($data["tva"])) : ?>
        <p>Aucune TVA enregistrée actuellement !</p>
        <?php else: ?>
        <section class="leftElement">
            <?php foreach($data["tva"] as $tva) : ?>
            <article class="dispositionCategories">
                <p <?php if($tva['activate']==0){ ?>class="inactif"<?php } ?>><?= htmlspecialchars($tva['name']) ?></p>

                <form method="POST" action="index.php?route=activationTva&id=<?= $tva['id'] ?>">
    
                    <input  type    = "hidden"
                            name    = "id"
                            value   =  "<?= $tva['id'] ?>" >
        
                    <input  type    = "hidden"
                            name    = "token"
                            value   =   <?php foreach($_SESSION['tokenGestionTva'] as $elem) : ?>
                                            <?php if(intval($elem['id']) == $tva['id']) : ?>
                                                <?= $elem['token'] ?>
                                            <?php endif; ?>
                                        <?php endforeach; ?>
                    >
        
                    <input  type    = "submit"
                            name    = "submit"
                            <?php   if($tva['activate']==1){
                                        echo'   value   = "Désactiver"
                                                class   = "btn colorYellow"
                                            ';}
                                    else{
                                        echo'   value   = "Activer"
                                                class   = "btn colorGreen"
                                            ';}
                            ?>
                    >
                </form>
            </article>
            <?php endforeach; ?>
        </section>
        <?php endif; ?>
    
        <div class="rightElement">
            <section>
                <form method="POST" action="index.php?route=addTva" id="addTvaForm" enctype="multipart/form-data">
        
                    <h2>Ajouter une TVA</h2>
                    <legend>Merci de renseigner les information suivantes :</legend>

                    <fieldset>
                        <label  for     = "tvaValue">Taux de la TVA</label>
                        <input  type    = "text"
                                id      = "tvaValue"
                                name    = "tvaValue"
                                placeholder   = "exemple : 2.4">
                        <small id="errorTva">Veuillez entrer une valeur entre 0 et 100 avec maximum une décimale séparée par un point</small>
                    </fieldset>
    
                    <fieldset>
                            <input  type    = "hidden"
                                    name    = "token"
                                    value   = "<?= $token ?>">
                    </fieldset>
        
                    <fieldset>
                            <input  type    = "submit"
                                    name    = "submit"
                                    value   = "Ajouter"
                                    class   = "btn colorGreen">
                    </fieldset>
                </form>
                <section>
                <?php require_once('views/bases/_errors.phtml'); ?>
                <?php require_once('views/bases/_valids.phtml'); ?>
                </section>
            </section>
        </div>
    </section>
    <script src="assets/js/preview.js"></script>
    <script type="module" src="assets/js/form.js"></script>
</main>