<section>
    <h1>ACCUEIL</h1>
</section>
<section class="accueil">

    <a href="index.php?route=addArticle"        class="btn colorYellow">Ajout article</a>
    <a href="index.php?route=addOption"         class="btn colorYellow">Ajout option</a></li>
    <a href="index.php?route=addCategorie"      class="btn colorYellow">Gestion des catégories</a></li>
    <a href="index.php?route=addTva"            class="btn colorYellow">Gestion des TVA</a></li>
    <a href="index.php?route=addPaiementMode"   class="btn colorYellow">Ajout Mode Paiement</a></li>


    <a href="index.php?route=customers"     class="btn">Liste utilisateurs</a></li>
    <a href="index.php?route=home"          class="btn">Gestion des commandes</a>
    <a href="index.php?route=home"          class="btn">Gestion cartes fidélité</a>
    <a href="index.php?route=home"          class="btn">Gestion des coupons clients</a>

    <a href="index.php?route=home"          class="btn">Gestion des réductions</a>
    <a href="index.php?route=home"          class="btn">Statistiques</a>
    <a href="index.php?route=home"          class="btn">Facturations</a>
    <a href="index.php?route=home"          class="btn">Gestion des stocks</a>
    <a href="index.php?route=home"          class="btn">Edition bilans</a>

    <a href="index.php?route=home"          class="btn colorRed">Ouverture Caisse</a>
    <a href="index.php?route=home"          class="btn colorRed">Gestion des alertes</a>

</section>