<main id="home">
    <section>
        <h1>ACCUEIL</h1>
    </section>
    <section class="accueil">
    
        <a href="index.php?route=articleGestion"    class="btn colorYellow">Gestion des articles</a>
        <a href="index.php?route=addCategorie"      class="btn colorYellow">Gestion des catégories</a></li>
        <a href="index.php?route=addTva"            class="btn colorYellow">Gestion des TVA</a></li>
        <a href="index.php?route=addPaymentMethod"  class="btn colorYellow">Gestion des Modes Paiement</a></li>
    
    
        <a href="index.php?route=customers"     class="btn colorYellow">Gestion des comptes clients</a></li>
        <a href="index.php?route=home"          class="btn">Gestion des commandes</a>
        <a href="index.php?route=home"          class="btn">Gestion cartes fidélité</a>
        <a href="index.php?route=home"          class="btn">Gestion des coupons clients</a>
    
        <a href="index.php?route=home"          class="btn">Gestion des réductions</a>
        <a href="index.php?route=statistics"    class="btn colorYellow">Statistiques</a>
        <a href="index.php?route=home"          class="btn">Facturations</a>
        <a href="index.php?route=home"          class="btn">Gestion des stocks</a>
        <a href="index.php?route=home"          class="btn">Edition bilans</a>
    
        <a href="index.php?route=home"          class="btn colorRed">Ouverture Caisse</a>
        <a href="index.php?route=home"          class="btn colorRed">Gestion des alertes</a>
        <a href="index.php?route=home"          class="btn colorRed">Cahier des pertes</a>
    
    </section>
</main>
