
    <form class="form" method="POST" action="index.php?route=submitFormAddLink" enctype="multipart/form-data">
        <input type='hidden' name="articleId" value="<?= $_GET['id']?>">
        <section>
<?php 
if(empty($optionsFind)){
?> <small>Il n'y a pas d'article dans cette catégorie !</small>
<?php
}
else{
foreach($optionsFind as $option): 

?>
    <div>        
            <input type="checkbox" name="optionId[]" value="<?= htmlspecialchars($option['id']) ?>">
                <img src="assets/uploads/options/<?= htmlspecialchars($option['categoriesCondiments_id'])?>/<?= htmlspecialchars($option['picture']) ?>">
                    <p><?= htmlspecialchars($option['name']) ?></p>
                
                    </p><?= htmlspecialchars($option['price']) ?> €</p>    
    </div>
<?php
endforeach;
}
?> </section>
<?php
if(!empty($optionsFind)){?>
    <input      type    = "submit"
                id      = "linkSubmit"
                name    = "submit"
                value   = "Joindre"
                class   = "btn colorGreen">
<?php } ?> 
    </form>

