<!-- <?php var_dump($data); ?> -->
<main id ="updateCustomers">
        
        <a href="index.php?route=displayOneCustomer&id=<?= $customer['id'] ?>" id="retour" class="btn"><i class="fa-solid fa-chevron-left"></i></a>
        <h1>Modification du compte</h1>

        <?php   if(empty($data['customer'])){
                        require_once('views/bases/_errors.phtml');
                        require_once('views/bases/_valids.phtml');
                }
                else{?>

        <form id="updateCustomerForm" method="POST" action="index.php?route=updateCustomer&id=<?= $customer['id'] ?>" enctype="multipart/form-data">

                <legend>Merci de renseigner les informations suivantes</legend>

                <?php require_once('views/bases/_errors.phtml'); ?>
                <?php require_once('views/bases/_valids.phtml'); ?>

                <section <?php if($data['customer']['valids_id']==3){echo'class="inactif"';}?>>

                        <fieldset>
                                <label  for     = "lastname">Nom</label>
                                <input  type    = "text"
                                        id      = "lastname"
                                        name    = "lastname"
                                        value   = "<?= $data['customer']['lastname']; ?>"
                                >
                                <small id="errorLastName">Votre nom doit comprendre entre 2 et 50 caractères</small>
                        </fieldset>

                        <fieldset>
                                <label  for     = "firstname">Prénom</label>
                                <input  type    = "text"
                                        id      = "firstname"
                                        name    = "firstname"
                                        value   = "<?= $data['customer']['firstname']; ?>"
                                >
                                <small id="errorFirstName">Votre prénom doit comprendre entre 2 et 50 caractères</small>
                        </fieldset>        

                        <fieldset>
                                <label  for     = "birthday">Date de naissance</label>
                                <input  type    = "date"
                                        id      = "birthday"
                                        name    = "birthday"
                                        value   = "<?= $data['customer']['birthday']; ?>">
                                <small id="errorBirthday">Merci de rentrer une date de naissance valide</small>
                        </fieldset>

                        <fieldset>
                                <label  for     = "rfid">RFID</label>
                                <input  type    = "text"
                                        id      = "rfid"
                                        name    = "rfid"
                                        value   = "<?= $data['customer']['rfid']; ?>">
                                <small id="errorRfid">Votre RFID doit contenir 10 chiffres (ce champ n'est pas obligatoire)</small>
                        </fieldset>

                        <fieldset>
                                <input  type    = "hidden"
                                        name    = "token"
                                        value   = "<?= $token ?>">
                        </fieldset>

                </section>
                <fieldset <?php if($data['customer']['valids_id']==3){echo'class="inactif"';}?>>
                                <input  type    = "submit"
                                        name    = "submit"
                                        value   = "Mettre à jour"
                                        class   = "btn colorGreen">
                </fieldset>
        </form>
        <?php } ?>

<script src="assets/js/preview.js"></script>
<script type="module" src="assets/js/form.js"></script>
</main>
<!-- <script>
            if ( window.history.replaceState ) {
                console.log(window.history.replaceState);
                window.history.replaceState( null, null, '/index.php?route=updateCustomer&id=34' );
            }
</script> -->
