<!-- <?php var_dump($data) ?> -->
<main id="statistic">

        <a href="index.php?route=statistics" id="retour" class="btn"><i class="fa-solid fa-chevron-left"></i></a>
        <h1>Chiffres d'affaires par article et par mois !</h1>

        <table>
                <thead>
                        <tr>
                                <th>Date</th>
                                <th>Article</th>
                                <th>Quantité</th>
                                <th>Total</th>
                        </tr>
                </thead>

        <?php
        $mois_precedent = '';
        foreach($statistiques as $elem) {
            // vérifier si le jour a changé
            if ($elem['mois'] != $mois_precedent) {
                echo "<tr class=\"date\"><td>" . $elem['newDate'] . "</td><td></td><td></td><td></td></tr>";
                // mettre à jour la variable pour stocker le jour précédent
                $mois_precedent = $elem['mois'];
            }
            echo "<tr>";
            echo "<td></td>";
            echo "<td>" . $elem['article'] . "</td>";
            echo "<td>" . $elem['quantite_vendue'] . "</td>";
            echo "<td>" . $elem['total_vendu'] . "€</td>";
            echo "</tr>";
        }

        echo "</table>";
        ?>
</main>
