<?php var_dump($data) ?>
<main id="statistic">

        <a href="index.php?route=statistics" id="retour" class="btn"><i class="fa-solid fa-chevron-left"></i></a>
        <h1>Chiffres d'affaires par article et par jour !</h1>

        <table>
                <thead>
                        <tr>
                                <th>Date</th>
                                <th>Article</th>
                                <th>Quantité</th>
                                <th>Total</th>
                        </tr>
                </thead>
                <tbody>
                        <?php foreach ($statistiques as $ligne): ?>
                                <tr>
                                        <td><?= date_format(date_create($ligne['date']), 'd-m-Y'); ?></td>
                                        <td><?= $ligne['article']; ?></td>
                                        <td><?= $ligne['quantite_vendue']; ?></td>
                                        <td><?= $ligne['total_vendu']; ?>€</td>
                                </tr>
                        <?php endforeach; ?>
                </tbody>
        </table>
</main>
