<!-- <?php var_dump($data) ?> -->
<main id="statistic">

        <a href="index.php?route=<?php   if($_SESSION['previousPage'] == 'statistics'){
                        echo "statistics";
                }
                else{
                        echo "getStatsForDay";
                } 
        ?>" id="retour" class="btn"><i class="fa-solid fa-chevron-left"></i></a>
        <?php if(!isset($_GET['day']) && !isset($_POST['date'])){ ?>
        <h1>Ventes par article et par jour !</h1>
        <?php } else{ ?>
        <h1>Ventes par article pour le <?= date_format(date_create($date), 'd-m-Y'); ?> !</h1>
        <?php } ?>

        <form method="POST" action="index.php?route=getStatistiquesByOneDay">
                <label for="start">Merci de selectionner une date : </label>
                <input  type    = "date"
                        id      = "date"
                        name    = "date"
                        <?php if(isset($_POST['date'])){ ?>
                                value   = "<?= $_POST['date'] ?>"
                        <?php } elseif(isset($_GET['day'])){ ?>
                                value   = "<?= $_GET['day'] ?>"
                        <?php } else{ ?>
                                value   = "<?= date("Y-m-d", time()); ?>"
                        <?php } ?>
                        onChange= "submit()">
        </form>

        <table>
                <thead>
                        <tr>
                                <th>Articles</th>
                                <th>Quantités vendues</th>
                                <th>Total</th>
                        </tr>
                </thead>
                <tbody>
                        <?php $qty = 0; $total = 0; foreach($statistiques as $ligne): ?>
                                <tr>
                                        <td><?= $ligne['article']; ?></td>
                                        <td><?= $ligne['quantite_vendue']; ?></td>
                                        <td><?= $ligne['total_vendu']; ?>€</td>
                                        <?php $qty = $qty+intval($ligne['quantite_vendue']); ?>
                                        <?php $total = $total+$ligne['total_vendu']; ?>
                                </tr>
                        <?php endforeach; ?>
                        <tr>
                                <th>TOTAL</th>
                                <th><?= $qty; ?></th>
                                <th><?= number_format($total, 2); ?>€</th>
                        </tr>
                </tbody>
        </table>

</main>
