<!-- <?php var_dump($data) ?> -->
<main id="statistic">

        <a href="index.php?route=statistics" id="retour" class="btn"><i class="fa-solid fa-chevron-left"></i></a>
        <h1>Toutes les commandes</h1>

        <table>
                <thead>
                        <tr>
                                <th>ID commande</th>
                                <th>Date de la commande</th>
                                <th>Méthode de paiement</th>
                                <th>Total (€)</th>
                                <th>Payée (€)</th>
                                <th>Rendue (€)</th>
                                <th>ID article</th>
                                <th>Quantité</th>
                                <th>Prix unitaire (€)</th>
                        </tr>
                </thead>


                <tbody>

                <?php 
                $previousOrderId = null;
                foreach ($statistiques as $row){
                        if ($row['id'] != $previousOrderId){
                                echo "<tr class=\"date\">";
                                echo "<td>" . $row['id'] . "</td>";
                                echo "<td>" . $row['dateTaken'] . "</td>";
                                echo "<td>" . $row['paymentMethod'] . "</td>";
                                echo "<td>" . number_format($row['total'], 2) . "</td>";
                                echo "<td>" . number_format($row['given'], 2) . "</td>";
                                echo "<td>" . number_format($row['rendu'], 2) . "</td>";
                                echo "<td></td>";
                                echo "<td></td>";
                                echo "<td></td>";
                                echo "</tr>";
                                $previousOrderId = $row['id'];
                                echo "<tr>";
                                echo "<td></td>";
                                echo "<td></td>";
                                echo "<td></td>";
                                echo "<td></td>";
                                echo "<td></td>";
                                echo "<td></td>";
                                echo "<td>" . $row['article_name'] . "</td>";
                                echo "<td>" . $row['quantity'] . "</td>";
                                echo "<td>" . number_format($row['unitary_price'], 2) . "</td>";
                                echo "</tr>";

                        }
                        else{
                                echo "<tr>";
                                echo "<td></td>";
                                echo "<td></td>";
                                echo "<td></td>";
                                echo "<td></td>";
                                echo "<td></td>";
                                echo "<td></td>";
                                echo "<td>" . $row['article_name'] . "</td>";
                                echo "<td>" . $row['quantity'] . "</td>";
                                echo "<td>" . number_format($row['unitary_price'], 2) . "</td>";
                                echo "</tr>";
                        }
                } ?>

                </tbody>
        </table>
</main>
