<!-- <?php var_dump($data); ?> -->
<main id="statistic">

        <a href="index.php?route=statistics" id="retour" class="btn"><i class="fa-solid fa-chevron-left"></i></a>

        <?php if(isset($_POST) && empty($_POST)){ ?>
        <h1>Ventes par catégorie</h1>
        <?php } else{ ?>
        <h1>Ventes pour la catégorie :  <?= $_POST["selectCategorie"] ?></h1>
        <?php } ?>

        <form method="POST" action="index.php?route=getStatsForCategories">
                <label for="selectCategorie">Merci de selectionner une catégorie : </label>
                <select name="selectCategorie" id="selectCategorie" onChange="submit()">
                        <option value="Choisir une catégorie">Choisir une catégorie</option>
                        <?php foreach($statistiques as $elem){ ?>
                                <option value="<?= $elem['categorie'] ?>"><?= $elem['categorie'] ?></option>
                        <?php } ?>
                </select>
        </form>


        <?php if(isset($_POST) && !empty($_POST['selectCategorie'])){ ?>
        <table>
                <thead>
                        <tr>
                                <th>Date</th>
                                <th>Catégorie</th>
                                <th>Quantité</th>
                                <th>Total</th>
                        </tr>
                </thead>

        <?php
        $mois_precedent = '';
        foreach($statistiques as $elem) {
                if($elem['categorie'] == $_POST['selectCategorie']){
                                        // vérifier si le jour a changé
                        if ($elem['mois'] != $mois_precedent) {
                                echo "<tr class=\"date\"><td>" . $elem['newDate'] . "</td><td></td><td></td><td></td></tr>";
                                // mettre à jour la variable pour stocker le jour précédent
                                $mois_precedent = $elem['mois'];
                        }
                        echo "<tr>";
                        echo "<td></td>";
                        echo "<td>" . $elem['categorie'] . "</td>";
                        echo "<td>" . $elem['quantite_vendue'] . "</td>";
                        echo "<td>" . $elem['total_vendu'] . "€</td>";
                        echo "</tr>";
                }
        }
        echo "</table>";
        ?>
        <?php } ?>
</main>
