<main id ="statistics">
        
        <a href="index.php" id="retour" class="btn"><i class="fa-solid fa-chevron-left"></i></a>
        <h1>Statistiques des ventes !</h1>

        <section>
                <section>
                        <h2>Chiffres d'affaire</h2>
                        <section>
                                <a href="index.php?route=getStatsForDay" class="btn colorGreen"><i class="fa-solid fa-chart-line"></i> Chiffre d'affaire par jour</a>
                                <a href="index.php?route=getStatsForMonth" class="btn colorGreen"><i class="fa-solid fa-chart-line"></i> Chiffre d'affaire par Mois</a>
                                <a href="index.php?route=getStatsForYear" class="btn colorGreen"><i class="fa-solid fa-chart-line"></i> Chiffre d'affaire par Année</a>
                        </section>
                </section>
                <section>
                        <h2>Statistiques par Période</h2>
                        <section>
                                <a href="index.php?route=getStatistiquesByOneDay" class="btn colorGreen"><i class="fa-solid fa-chart-line"></i> Statistiques par jour</a>
                                <a href="index.php?route=getAllOrders" class="btn"><i class="fa-solid fa-chart-line"></i> Tous les commandes</a>
                        </section>
                </section>
                <section>
                        <h2>Statistiques par Articles</h2>
                        <section>
                                <a href="index.php?route=getStatsForArticles" class="btn colorYellow"><i class="fa-solid fa-chart-line"></i> Statistiques par Article</a>
                                <a href="index.php?route=getAllStatistiquesForArticleAndDay" class="btn colorGreen"><i class="fa-solid fa-chart-line"></i> Statistiques par Article/Jour</a>
                                <a href="index.php?route=getAllStatistiquesForArticleAndMonth" class="btn colorGreen"><i class="fa-solid fa-chart-line"></i> Statistiques par Article/Mois</a>
                                <a href="index.php?route=getAllStatistiquesForArticlesAndYear" class="btn colorGreen"><i class="fa-solid fa-chart-line"></i> Statistiques par Article/Année</a>
                        </section>
                </section>
                <section>
                        <h2>Statistiques par Catégorie</h2>
                        <section>
                                <a href="index.php?route=getStatsForCategories" class="btn"><i class="fa-solid fa-chart-line"></i> Statistiques par Catégorie</a>
                                <a href="index.php?route=getAllStatistiquesForCategoriesAndDay" class="btn"><i class="fa-solid fa-chart-line"></i> Statistiques par Catégorie/Jour</a>
                                <a href="index.php?route=getAllStatistiquesForCategoriesAndMonth" class="btn"><i class="fa-solid fa-chart-line"></i> Statistiques par Catégorie/Mois</a>
                                <a href="index.php?route=getAllStatistiquesForCategoriesAndYear" class="btn"><i class="fa-solid fa-chart-line"></i> Statistiques par Catégorie/Année</a>
                        </section>
                </section>
        </section>





</main>