<!-- <?php var_dump($data) ?> -->
<main id="statistic">

        <a href="index.php?route=statistics" id="retour" class="btn"><i class="fa-solid fa-chevron-left"></i></a>
        <h1>Chiffres d'affaires par jour !</h1>

        <table>
                <thead>
                        <tr>
                                <th>Date</th>
                                <th>Total Vendu</th>
                                <th></th>
                        </tr>
                </thead>
                <tbody>
                        <?php foreach ($statistiques as $ligne): ?>
                                <tr>
                                        <td><?= date_format(date_create($ligne['jour']), 'd-m-Y'); ?></td>
                                        <td><?= $ligne['total_vendu']; ?>€</td>
                                        <td><a href="index.php?route=getStatistiquesByOneDay&day=<?= date_format(date_create($ligne['jour']), 'Y-m-d'); ?>" class="btn colorYellow">Détail</a></td>
                                </tr>
                        <?php endforeach; ?>
                </tbody>
        </table>
</main>
