<!-- <?php var_dump($data) ?> -->
<main id="statistic">

        <a href="index.php?route=statistics" id="retour" class="btn"><i class="fa-solid fa-chevron-left"></i></a>
        <h1>Chiffres d'affaires par année !</h1>

        <table>
                <thead>
                        <tr>
                                <th>Année</th>
                                <th>Chiffre d'affaire</th>
                        </tr>
                </thead>
                <tbody>
                        <?php foreach ($statistiques as $ligne): ?>
                                <tr>
                                        <td><?= $ligne['annee']; ?></td>
                                        <td><?= $ligne['total_vendu']; ?>€</td>
                                </tr>
                        <?php endforeach; ?>
                </tbody>
        </table>
</main>
