<footer>
    <nav>
        <a href="index.php?route=later"><i class="fa-solid fa-user-clock"></i></i>Remis plus tard</a>
        <a href="index.php?route=standBy"><i class="fa-brands fa-creative-commons-nc-eu"></i></i>Attente règlement</a>
        <a href="index.php?route=lien"><i class="fa-solid fa-person"></i>Lien 3</a>
        <a href="index.php?route=lien"><i class="fa-solid fa-person"></i>Lien 4</a>
        <a href="index.php?route=lien"><i class="fa-solid fa-person"></i>Lien 5</a>
    </nav>
</footer>