<header id="main_header">
    <nav>
        <a href="index.php?route=home" class="logo">ARDOISE</a>
        <ul>
            <li><a href="index.php?route=home"><i class="fa-solid fa-person"></i>...</a></li>
            <li><a href="index.php?route=operators"><i class="fa-solid fa-person-dots-from-line"></i>Opérateurs</a></li>
            <li><a href="index.php?route=categories"><i class="fa-solid fa-bars"></i>Catégories</a></li>
            <li><a href="index.php?route=categories"><i class="fa-solid fa-cash-register"></i>Caisse</a></li>
            <li><a href="index.php?route=home"><i class="fa-solid fa-chart-line"></i>...</a></li>
            <li><a href="index.php?route=home"><i class="fa-solid fa-circle-plus"></i>....</a></li>
            <li><a href="index.php?route=screens"><i class="fa-solid fa-display"></i>Ecrans</a></li>
            <li><a href="index.php?route=readBasket"><i class="fa-solid fa-cart-shopping"></i></a></li>
        </ul>
    </nav>
</header>
